name: Deploy-auth

on:
  push:
    branches:
      - "main"
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Build docker image
    - uses: actions/checkout@v3
    - run: |
        cd auth && docker build -t einmex/auth .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push einmex/auth
